updated files

diff --git a/.github/workflows/generate-ascii.yml b/.github/workflows/generate-ascii.yml
--- a/.github/workflows/generate-ascii.yml
+++ b/.github/workflows/generate-ascii.yml
@@ -1,4 +1,4 @@
-name: Generate ASSCII Artwork
+name: Generate ASCII Artwork
 
 on:
   push
@@ -8,12 +8,17 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repo
-      uses: actions/checkout@v4
+      uses: actions/checkout@v3 # Use stable version
 
     - name: List Repo Files
       run: ls -ltra
 
-    - name: Executing Shell Script
+    - name: Execute Shell Script
       run: |
-        chmod +x ascii-script.sh
-        ./ascii-script.sh
+        if [ -f "ascii-script.sh" ]; then
+          chmod +x ascii-script.sh
+          ./ascii-script.sh
+        else
+          echo "ascii-script.sh not found. Exiting."
+          exit 1
+        fi
